### ISSUE TITLE
NO log in to dashboard

### ISSUE THREAD

**Issue by aserratorta** [Flexible-User-Experience/pas-a-repas#33]
I can log in to the new dashboard since sonata was installed.
I tried to put the same user and password that i had in the parameters.yml, but it doesn't work.
![image](https://cloud.githubusercontent.com/assets/12971681/12081509/81d08e3c-b27b-11e5-91be-cdc4f2fd3300.png)

**Comment by davidromani** [comment]
This is because I've installed SonataUserBundle and now the users are persited into a DB table. Read the new Symfony "fos:user:<...>" commands help. You need to create a new user and promote it with a ROLE_SUPER_ADMIN role.

Always rember to apply "composer install" command after composer.lock changes.

**Comment by aserratorta** [comment]
After migrations, I can't log in to dashboard again.
And I don't remember how you fixed. I didn't write down any note.

**Comment by davidromani** [comment]
Because your database is empty. All you need is to load fixtures, easy enough?

Remember that Sonata Use Bundle stores all users and roles into database itself (User & Group Entities).

**Comment by aserratorta** [comment]
:flushed:
