### ISSUE TITLE
Set contact email destination configurable

### ISSUE THREAD

**Issue by davidromani** [Flexible-User-Experience/pas-a-repas#8]
We need to change the contact form email destination as a dynamic part. Inside a controller you can read a config parameter like this:

```
$this->container->getParameter('my_parameters_yml_key')
```

Apply this strategy on src/AppBundle/Controller/DefaultController line 54

**Comment by aserratorta** [comment]
Hi David, 
After pulling your commits Sunday night I couldn't render anything. It appears this message:
![captura de pantalla 2015-11-30 a les 22 20 02](https://cloud.githubusercontent.com/assets/12971681/11484844/986dd2f2-97b0-11e5-8419-323bb9350595.png)
I found out this solution in this forum http://stackoverflow.com/questions/33023299/symfony2-you-have-requested-a-non-existent-parameter, but it doesn't work. I wanted to try composer update, but I prefer talking to you before.

So I can't solve this issue, because I can't push my commit.

Let's see on Wednesday :disappointed:

**Comment by davidromani** [comment]
This is because I added a new parameter key config. Composer update should be enough to solve the problem.
